---
- hosts: all
  tasks:
  
  - name: définir des variables
    ansible.builtin.set_fact:
      var_username: "{{ lookup('env', 'demo_username') }}"
      var_password: "{{ lookup('env', 'demo_password') }}"
     
  - name: définir des variables
    ansible.builtin.set_fact:
      var_credential: "{{ var_username }}:{{ var_password }}"
 
  - name: Display Username
    ansible.builtin.debug:
      var: var_username

  - name: Display password
    ansible.builtin.debug:
      var: var_password

  - name: Display Credential
    ansible.builtin.debug:
      var: var_credential
