---
- hosts: server-4.scc-edu
  become: yes

  tasks:

  - name: Ensure group "ansible" exists
    ansible.builtin.group:
      name: ansible
      state: present

  - name: create ansible user
    ansible.builtin.user:
      name: ansible
      group: ansible

  - name: creation du dossier .ssh si non existe
    ansible.builtin.file:
      path: /home/ansible/.ssh
      state: directory
      owner: ansible
      group: ansible
      mode: '0700'

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/cloud/.ssh/authorized_keys
      dest: /home/ansible/.ssh/authorized_keys
      owner: ansible
      group: ansible
      mode: '0644'
      